name: flutter_advanced_networkimage_2
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 2.0.1
repository: https://github.com/insinfo/flutter_advanced_networkimage

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  pool: ^1.5.1
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.9.0"
